import { Reveal } from './Reveal'
import { GrassStrip, Sparkle } from './Pixel'

export function Showcase() {
  return (
    <section id="showcase" className="relative overflow-hidden">
      <GrassStrip flip />
      <div className="bg-[#dcedd2] py-24 md:py-36">
        <div className="mx-auto max-w-6xl px-4">
          <div className="grid gap-12 md:grid-cols-12 md:items-end">
            <Reveal className="md:col-span-5">
              <p className="font-pixel text-[11px] tracking-wide text-grass-dark uppercase">
                ✦ One-shot builds
              </p>
              <h2 className="font-display mt-4 text-[clamp(2.2rem,5vw,3.8rem)] leading-[1.02] font-bold tracking-[-0.02em]">
                A few words in, a <span className="text-grass">house</span> out.
              </h2>
            </Reveal>
            <Reveal delay={0.1} className="md:col-span-7">
              <p className="max-w-lg text-[16.5px] leading-relaxed text-stone md:ml-auto">
                No schematics, no templates. The model plans the whole
                structure from scratch, writes the builder code, and Minedit
                runs it inside your world.
              </p>
            </Reveal>
          </div>

          <Reveal delay={0.15} className="mt-14">
            <div className="relative">
              <Sparkle className="sparkle absolute -top-6 right-10 z-10 w-5" />
              <Sparkle
                className="sparkle absolute -bottom-5 left-14 z-10 w-4"
                color="#79c465"
                style={{ animationDelay: '1.4s' }}
              />
              <div className="mc-raised p-2">
                <div className="relative overflow-hidden border-2 border-ink/20">
                  <img
                    src="/media/example-build.png"
                    alt="A cute cottage generated by AI from a single prompt"
                    className="block w-full"
                    loading="lazy"
                  />
                  <div className="absolute bottom-4 left-4 flex items-center gap-3 border-2 border-black/50 bg-[#211e16]/92 px-4 py-2.5">
                    <span className="font-mono text-[13px] text-leaf">/build</span>
                    <span className="font-mono text-[13px] text-[#f0ede2]">a cute house</span>
                  </div>
                </div>
              </div>
            </div>
          </Reveal>
        </div>
      </div>
      <GrassStrip />
    </section>
  )
}
